Temporary compatibility layer for numhosts property support.
Temporary fix: AttributeError: 'IPNetwork' object has no attribute 'numhosts'

Change-Id: Ic3b18de3fc3b3e37cd6250a8e26ff010a3a6d80c
(cherry picked from commit ce22b15)